const userCollection = [
    // {
    //     userID: "1",
    //     name: "",
    //     gender: "",
    //     ethnicity: "",
    //     region: "",
    //     college: "",
    //     schoolYear: "",
    //     isPrevMentor: "",
    //     schedule: {
    //         Monday: [],
    //         Tuesday: [],
    //         Wednesday: [],
    //         Thursday: [],
    //         Friday: [],
    //     },
    //     hasCar: "",
    //     languagesSpoken: "",
    //     shirstSize: "",
    //     canTeachMultipleDays: "",
    // },
    {
        key: "1",
        name: "Mariam Gould",
        gender: "Male",
        ethnicity: "Asian or Pacific Islander",
        region: "Orange County",
        college: "University of California, Irvine",
        schoolYear: "3rd",
        isPrevMentor: false,
        schedule: {
            Monday: ["3:00 PM - 5:00 PM","3:30 PM - 5:30 PM","3:45 PM - 5:45 PM"],
            Tuesday: [],
            Wednesday: ["3:00 PM - 5:00 PM"],
            Thursday: [],
            Friday: ["3:00 PM - 5:00 PM","3:30 PM - 5:30 PM","3:45 PM - 5:45 PM"],
        },
        hasCar: false,
        languagesSpoken: "Korean",
        shirstSize: "M",
        canTeachMultipleDays: false,
    },
    {
        key: "2",
        name: "Alessia Mcgowan",
        gender: "Male",
        ethnicity: "Asian or Pacific Islander",
        region: "Orange County",
        college: "California State Univeristy, Fullerton",
        schoolYear: "4th+",
        isPrevMentor: true,
        schedule: {
            Monday: ["3:00 PM - 5:00 PM"],
            Tuesday: [],
            Wednesday: ["3:00 PM - 5:00 PM"],
            Thursday: [],
            Friday: [],
        },
        hasCar: true,
        languagesSpoken: "I do not speak any other languages",
        shirstSize: "L",
        canTeachMultipleDays: false,
    },
    {
        key: "3",
        name: "Katarina Andrew",
        gender: "Female",
        ethnicity: "African American",
        region: "Riverside",
        college: "University of California, Riverside",
        schoolYear: "4th+",
        isPrevMentor: true,
        schedule: {
            Monday: [],
            Tuesday: ["3:00 PM - 5:00 PM", "3:30 PM - 5:30 PM"],
            Wednesday: [],
            Thursday: ["3:00 PM - 5:00 PM", "3:30 PM - 5:30 PM"],
            Friday: [],
        },
        hasCar: true,
        languagesSpoken: "Japanese",
        shirstSize: "M",
        canTeachMultipleDays: false,
    },
    {
        key: "4",
        name: "Addie Page",
        gender: "Male",
        ethnicity: "Hispanic or Latino",
        region: "Orange County",
        college: "University of California, Irvine",
        schoolYear: "2nd",
        isPrevMentor: false,
        schedule: {
            Monday: ["3:00 PM - 5:00 PM", "3:30 PM - 5:30 PM"],
            Tuesday: ["3:00 PM - 5:00 PM"],
            Wednesday: ["3:00 PM - 5:00 PM", "3:30 PM - 5:30 PM"],
            Thursday: ["3:00 PM - 5:00 PM"],
            Friday: ["3:00 PM - 5:00 PM"],
        },
        hasCar: true,
        languagesSpoken: "Spanish",
        shirstSize: "S",
        canTeachMultipleDays: "Yes",
    },
    {
        key: "5",
        name: "Lester Wade",
        gender: "Male",
        ethnicity: "Asian or Pacific Islander",
        region: "Orange County",
        college: "University of California, Irvine",
        schoolYear: "3rd",
        isPrevMentor: false,
        schedule: {
            Monday: [],
            Tuesday: ["3:00 PM - 5:00 PM"],
            Wednesday: [],
            Thursday: ["3:00 PM - 5:00 PM"],
            Friday: [],
        },
        hasCar: true,
        languagesSpoken: "Korean, very little Spanish and German but still can communicate",
        shirstSize: "L",
        canTeachMultipleDays: false,
    },
    {
        key: "6",
        name: "Don Warner",
        gender: "Female",
        ethnicity: "Asian or Pacific Islander",
        region: "Orange County",
        college: "University of California, Irvine",
        schoolYear: "4th+",
        isPrevMentor: true,
        schedule: {
            Monday: ["3:30 PM - 5:30 PM","3:45 PM - 5:45 PM"],
            Tuesday: [],
            Wednesday: ["3:30 PM - 5:30 PM","3:45 PM - 5:45 PM"],
            Thursday: [],
            Friday: [],
        },
        hasCar: false,
        languagesSpoken: "Spanish",
        shirstSize: "S",
        canTeachMultipleDays: false,
    },
    {
        key: "7",
        name: "Shahid O'Doherty",
        gender: "Female",
        ethnicity: "Asian or Pacific Islander",
        region: "Riverside",
        college: "University of California, Riverside",
        schoolYear: "4th+",
        isPrevMentor: "Yes",
        schedule: {
            Monday: ["3:00 PM - 5:00 PM","3:30 PM - 5:30 PM","3:45 PM - 5:45 PM"],
            Tuesday: ["3:00 PM - 5:00 PM","3:30 PM - 5:30 PM",],
            Wednesday: ["3:00 PM - 5:00 PM","3:30 PM - 5:30 PM","3:45 PM - 5:45 PM"],
            Thursday: ["3:00 PM - 5:00 PM","3:30 PM - 5:30 PM",],
            Friday: [],
        },
        hasCar: true,
        languagesSpoken: "Urdu",
        shirstSize: "M",
        canTeachMultipleDays: false,
    },
];

export default userCollection;