export const instructorColumns = [
  { name: 'name', title: 'Name'},
  { name: 'gender', title: 'Gender'},
  { name: 'year_of_instruction', title: 'School Year'},
  { name: 'major', title: 'Major'},
  { name: 'university', title: 'University'},
  { name: 'region', title: 'Region'},
  { name: 'address', title: 'Address'},
  { name: 'car', title: 'Car 🚗', description:'Weather they have a car or not'},
  { name: 'returning_instructor', title: 'Returning'},
  { name: 'shirt_size', title: 'Shirt Size 👕'},
  { name: 'programs', title: 'Programs'},
  { name: 'languages_spoken', title: 'Languages'},
  { name: 'schedule', title: 'Schedule'},
  { name: 'city', title: 'City'},
  { name: 'phone_number', title: 'Phone Number'},
  { name: 'programs_teaching', title: 'Programs (for filtering)'},
];

export const instructorDefaultColumnWidths = [
  { columnName: 'name', width: 165 },
  { columnName: 'gender', width: 90 },
  { columnName: 'year_of_instruction', width: 130 },
  { columnName: 'major', width: 80 },
  { columnName: 'university', width: 110 },
  { columnName: 'region', width: 135 },
  { columnName: 'address', width: 185 },
  { columnName: 'car', width: 100 },
  { columnName: 'returning_instructor', width: 110 },
  { columnName: 'shirt_size', width: 130 },
  { columnName: 'programs', width: 250 },
  { columnName: 'languages_spoken', width: 180 },
  { columnName: 'schedule', width: 290},
  { columnName: 'city', width: 100},
  { columnName: 'phone_number', width: 100},
  { columnName: 'programs_teaching', width: 100},
];


export const instructorDefaultColumnOrder = [
  'name',
  'programs',
  'programs_teaching',
  'schedule',
  'region',
  'car',
  'major',
  'returning_instructor',
  'year_of_instruction',
  'university',
  'languages_spoken',
  'address',
  'shirt_size',
  'gender',
  'city',
  'phone_number',
];